#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use App\Service\TwitterServiceProvider;
use App\Service\GithubServiceProvider;

$config = [
    'app_path' => __DIR__ . '/app/Command'
];

if (is_file(__DIR__ . '/credentials.php')) {
    $config = array_merge($config, require __DIR__ . '/credentials.php');
}

$app = new App($config);
$app->addService('twitter', new TwitterServiceProvider());
$app->addService('github', new GithubServiceProvider());
$app->runCommand($argv);
